language: "node_js"
node_js:
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"

before_install:
  - "npm install -g istanbul"
  - "npm install -g coveralls"

script:
  - "NODE_PATH=lib yarn test"

sudo: false
