language: "node_js"
node_js:
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"

before_install:
  - "npm install -g istanbul"
  - "npm install -g coveralls"

script:
  - "NODE_PATH=lib make check"

after_success:
  - "NODE_PATH=lib make report-cov"

sudo: false
